# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_auto_20190326_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='posted_on',
        ),
    ]
