# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instaclone', '0003_auto_20190619_1628'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='item',
            index_together=set([('id', 'profile')]),
        ),
    ]
