# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_remove_comments_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instaclone.Profile'),
        ),
    ]
